# Generated by Django 2.2 on 2019-07-17 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='board',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='boards.Board'),
        ),
        migrations.AddField(
            model_name='topic',
            name='starter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
